# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: misterio92/ci-php-node

pipelines:
     branches:  # Pipelines that run automatically on a commit to a branch can also be triggered manually
          master:
             - step:
                  deployment: production
                  caches:
                    - composer
                  script:
                      - apt-get update && apt-get install -y unzip
                      - apt-get install -y zip
                      - apt-get install -y  python-dev
                      - apt-get install -y  gnupg
                      - curl -O https://bootstrap.pypa.io/get-pip.py
                      - npm install
                      - npm run prod
                      - python get-pip.py
                      - composer install
                      - pip install boto3==1.3.0 # required for beanstalk_deploy.py
                      - zip queproponen.zip -r * .[^.]* -x  node_modules/**\* .git/**\* .git* laradock/**\*  vendor/**\*  .env* # package up the application for deployment
                      - python beanstalk_deploy.py prod # run the deployment script
